const SERVER_HOST = process.env.API_URL

const getDate = (year, month, day) => {
    return {year, month, day}
}



const getReviews = () => {
    return [
        {
            estimates: 5,
            comment: 'Я ношу эту обувь уже много лет. Я очень люблю их!',
            person: 'Манас',
            date: getDate(2023, 1, 27),
        }, 
        {
            estimates: 5,
            comment: 'Размер соответствует размеру, очень удобные, очень нравятся цвета. купил бы снова',
            person: 'Аяна',
            date: getDate(2023, 1, 13),
        },
        {
            estimates: 5,
            comment: 'купил их для мамы на Рождество, и она любит их, учитывая тот факт, что она не любит теннисные туфли.',
            person: 'Аяна',
            date: getDate(2023, 1, 27),
        },
    ]
}

const getDescr = (name) => {
    return `Кроссовки ${name} с оригинальным волнистым дизайном, вдохновленным японскими сверхскоростными пассажирскими экспрессами, позволяют вам развивать свой стиль на полной скорости. Взяв за основу революционную вставку Nike Air во всю длин, которая потрясла мир бега, добавив свежие цвета и четкие детали, вы сможете кататься с первоклассным комфортом.`
}   

const getPhotos = (id) => {
    const initial = `${SERVER_HOST}images/products/${id}/`
    let slider = []

    for(let i = 1; i <= 4; i++) {
        slider.push(`${initial}slider/photo${i}.png`)
    }

    return {
        card: `${initial}card.jpg`,
        slider,
        secondPhoto: `${initial}second.png`,
        banner: `${initial}banner.jpg`
    }
}

let products = [
    {
        name: 'Air Jordan 1 Low',
        vendor: 2258,
        price: 9300,
        dimensions: [39, 40, 41,43, 44],
        colors: ['#E6E6E6', '#E0B20D', '#801FBD', '#5365A4', '#E40000'],
        categories: ['run', 'basketball', 'street'],
        brand: 'nike',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man', 'woman'],
        reviews: getReviews(),
        date: getDate(2023, 5, 15),
        photos: getPhotos('product1')
    },
    {
        name: 'Air Jordan 1 Retro High OG',
        vendor: 2259,
        price: 8500,
        dimensions: [39, 40, 41, 42, 44],
        colors: ['#375B3D', '#A5B8C9'],
        categories: ['basketball', 'street'],
        brand: 'nike',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 4, 21),
        photos: getPhotos('product2')
    },
    {
        name: 'Adidas Adistar 1',
        vendor: 2260,
        price: 8200,
        dimensions: [38, 41, 42, 43, 44],
        colors: ['#E2E2E2', '#544C2F', '#3F4DC9', '#3F4DC9', '#951212'],
        categories: ['street', 'run'],
        brand: 'adidas',
        season: 'summer',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man', 'woman'],
        reviews: getReviews(),
        date: getDate(2023, 6, 24),
        photos: getPhotos('product3')
    },
    {   
        name: 'Air Jordan 1 Zoom Comfort 2',
        vendor: 2261,
        price: 7800,
        dimensions: [39, 40, 41, 42, 43],
        colors: ['#E2E2E2', '#544C2F', '#3F4DC9', '#3F4DC9', '#951212'],
        categories: ['street', 'run'],
        brand: 'adidas',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 3, 13),
        photos: getPhotos('product4')
    },
    {   
        name: 'Air Jordan 7 Retro SE',
        vendor: 2262,
        price: 8000,
        dimensions: [39, 40, 42, 43, 44],
        colors: ['#A32020', '#E0B20D', '#E9E1EE', '#375B3D', '#A5B8C9'],
        categories: ['street', 'basketball'],
        brand: 'jordan',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 5, 8),
        photos: getPhotos('product5')
    },
    {   
        name: 'Air Jordan 1 Mid SE',
        vendor: 2263,
        price: 7600,
        dimensions: [39, 40, 41, 43, 44],
        colors: ['#F0AF72', '#7B3B0D', '#8B22CD', '#FFFFFF', '#C9A5C3'],
        categories: ['basketball'],
        brand: 'nike',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 3, 5),
        photos: getPhotos('product6')
    },
    {   
        name: 'Jordan Max Aura 4',
        vendor: 2264,
        price: 8300,
        dimensions: [39, 41, 42, 43, 44],
        colors: ['#74B3C1', '#BC128D', '#B51A1A', '#616161', '#A5B8C9'],
        categories: ['run', 'street'],
        brand: 'jordan',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 2, 2),
        photos: getPhotos('product7')
    },
    {   
        name: 'Air Jordan Dub Zero',
        vendor: 2265,
        price: 9000,
        dimensions: [37, 38, 39, 40, 41],
        colors: ['#FFAAAA', '#E3E3E3', '#4A4A4A', '#650FBB', '#FFFFFF'],
        categories: ['street'],
        brand: 'asics',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['woman'],
        reviews: getReviews(),
        date: getDate(2023, 10, 14),
        photos: getPhotos('product8')
    },
    {   
        name: 'Jordan Granville Pro',
        vendor: 2266,
        price: 8900,
        dimensions: [39, 40, 41, 42, 43],
        colors: ['#8DD8F8', '#D16CCD', '#E9E1EE', '#5041A9', '#65727D'],
        categories: ['street'],
        brand: 'rebook',
        season: 'summer',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 4, 19),
        photos: getPhotos('product9')
    },
    {   
        name: 'Jordan One Take 4',
        vendor: 2267,
        price: 8500,
        dimensions: [39, 40, 41, 42, 43],
        colors: ['#3F3F3F', '#C30DE0', '#641397', '#B24D59', '#C9BFA5'],
        categories: ['street', 'football'],
        brand: 'puma',
        season: 'summer',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 2, 16),
        photos: getPhotos('product10')
    },
    {   
        name: 'Jordan Stay Loyal 2',
        vendor: 2268,
        price: 8000,
        dimensions: [40, 41, 42, 43, 44],
        colors: ['#FCB0B0', '#6F9662', '#4F6899', '#D6E0F3', '#A5B8C9'],
        categories: ['street'],
        brand: 'puma',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 3, 15),
        photos: getPhotos('product11')
    },
    {   
        name: 'Jordan Series Mid',
        vendor: 2269,
        price: 8300,
        dimensions: [38, 39, 40, 43, 44],
        colors: ['#DCDCDC', '#8348BE', '#A2B163', '#CE9A89', '#C9A5C3'],
        categories: ['street', 'run'],
        brand: 'asics',
        season: 'summer',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man', 'woman'],
        reviews: getReviews(),
        date: getDate(2023, 2, 19),
        photos: getPhotos('product12')
    },
    {   
        name: 'Jordan Series ES',
        vendor: 2270,
        price: 8600,
        dimensions: [38, 39, 40, 43, 44],
        colors: ['#525252', '#B948BB', '#C02C2C', '#BA8E88', '#B2CA80'],
        categories: ['street', 'run', 'football'],
        brand: 'asics',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man', 'woman'],
        reviews: getReviews(),
        date: getDate(2023, 1, 17),
        photos: getPhotos('product13')
    },
    {   
        name: 'Jordan Access',
        vendor: 2271,
        price: 8000,
        dimensions: [39, 40, 42, 43, 44],
        colors: ['#E7E7E7', '#9D0DE0', '#5E599F', '#AD5E32', '#C9A5AB'],
        categories: ['street', 'run', 'football', 'basketball'],
        brand: 'rebook',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 5, 16),
        photos: getPhotos('product14')
    },
    {   
        name: 'Jordan Nu Retro 1 Low',
        vendor: 2272,
        price: 8200,
        dimensions: [39, 40, 41, 43, 44],
        colors: ['#3F3F3F', '#E0B20D', '#E9E1EE', '#375B3D', '#A5B8C9'],
        categories: ['run', 'football'],
        brand: 'adidas',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 2, 22),
        photos: getPhotos('product15')
    },
    {
        name: 'Air Jordan 1 Low',
        vendor: 2258,
        price: 9300,
        dimensions: [39, 40, 41,43, 44],
        colors: ['#E6E6E6', '#E0B20D', '#801FBD', '#5365A4', '#E40000'],
        categories: ['run', 'basketball', 'street'],
        brand: 'nike',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man', 'woman'],
        reviews: getReviews(),
        date: getDate(2023, 5, 15),
        photos: getPhotos('product1')
    },
    {
        name: 'Air Jordan 1 Retro High OG',
        vendor: 2259,
        price: 8500,
        dimensions: [39, 40, 41, 42, 44],
        colors: ['#375B3D', '#A5B8C9'],
        categories: ['basketball', 'street'],
        brand: 'nike',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 4, 21),
        photos: getPhotos('product2')
    },
    {
        name: 'Adidas Adistar 1',
        vendor: 2260,
        price: 8200,
        dimensions: [38, 41, 42, 43, 44],
        colors: ['#E2E2E2', '#544C2F', '#3F4DC9', '#3F4DC9', '#951212'],
        categories: ['street', 'run'],
        brand: 'adidas',
        season: 'summer',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man', 'woman'],
        reviews: getReviews(),
        date: getDate(2023, 6, 24),
        photos: getPhotos('product3')
    },
    {   
        name: 'Air Jordan 1 Zoom Comfort 2',
        vendor: 2261,
        price: 7800,
        dimensions: [39, 40, 41, 42, 43],
        colors: ['#E2E2E2', '#544C2F', '#3F4DC9', '#3F4DC9', '#951212'],
        categories: ['street', 'run'],
        brand: 'adidas',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 3, 13),
        photos: getPhotos('product4')
    },
    {   
        name: 'Air Jordan 7 Retro SE',
        vendor: 2262,
        price: 8000,
        dimensions: [39, 40, 42, 43, 44],
        colors: ['#A32020', '#E0B20D', '#E9E1EE', '#375B3D', '#A5B8C9'],
        categories: ['street', 'basketball'],
        brand: 'jordan',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 5, 8),
        photos: getPhotos('product5')
    },
    {   
        name: 'Air Jordan 1 Mid SE',
        vendor: 2263,
        price: 7600,
        dimensions: [39, 40, 41, 43, 44],
        colors: ['#F0AF72', '#7B3B0D', '#8B22CD', '#FFFFFF', '#C9A5C3'],
        categories: ['basketball'],
        brand: 'nike',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 3, 5),
        photos: getPhotos('product6')
    },
    {   
        name: 'Jordan Max Aura 4',
        vendor: 2264,
        price: 8300,
        dimensions: [39, 41, 42, 43, 44],
        colors: ['#74B3C1', '#BC128D', '#B51A1A', '#616161', '#A5B8C9'],
        categories: ['run', 'street'],
        brand: 'jordan',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 2, 2),
        photos: getPhotos('product7')
    },
    {   
        name: 'Air Jordan Dub Zero',
        vendor: 2265,
        price: 9000,
        dimensions: [37, 38, 39, 40, 41],
        colors: ['#FFAAAA', '#E3E3E3', '#4A4A4A', '#650FBB', '#FFFFFF'],
        categories: ['street'],
        brand: 'asics',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['woman'],
        reviews: getReviews(),
        date: getDate(2023, 10, 14),
        photos: getPhotos('product8')
    },
    {   
        name: 'Jordan Granville Pro',
        vendor: 2266,
        price: 8900,
        dimensions: [39, 40, 41, 42, 43],
        colors: ['#8DD8F8', '#D16CCD', '#E9E1EE', '#5041A9', '#65727D'],
        categories: ['street'],
        brand: 'rebook',
        season: 'summer',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 4, 19),
        photos: getPhotos('product9')
    },
    {   
        name: 'Jordan One Take 4',
        vendor: 2267,
        price: 8500,
        dimensions: [39, 40, 41, 42, 43],
        colors: ['#3F3F3F', '#C30DE0', '#641397', '#B24D59', '#C9BFA5'],
        categories: ['street', 'football'],
        brand: 'puma',
        season: 'summer',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 2, 16),
        photos: getPhotos('product10')
    },
    {   
        name: 'Jordan Stay Loyal 2',
        vendor: 2268,
        price: 8000,
        dimensions: [40, 41, 42, 43, 44],
        colors: ['#FCB0B0', '#6F9662', '#4F6899', '#D6E0F3', '#A5B8C9'],
        categories: ['street'],
        brand: 'puma',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 3, 15),
        photos: getPhotos('product11')
    },
    {   
        name: 'Jordan Series Mid',
        vendor: 2269,
        price: 8300,
        dimensions: [38, 39, 40, 43, 44],
        colors: ['#DCDCDC', '#8348BE', '#A2B163', '#CE9A89', '#C9A5C3'],
        categories: ['street', 'run'],
        brand: 'asics',
        season: 'summer',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man', 'woman'],
        reviews: getReviews(),
        date: getDate(2023, 2, 19),
        photos: getPhotos('product12')
    },
    {   
        name: 'Jordan Series ES',
        vendor: 2270,
        price: 8600,
        dimensions: [38, 39, 40, 43, 44],
        colors: ['#525252', '#B948BB', '#C02C2C', '#BA8E88', '#B2CA80'],
        categories: ['street', 'run', 'football'],
        brand: 'asics',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man', 'woman'],
        reviews: getReviews(),
        date: getDate(2023, 1, 17),
        photos: getPhotos('product13')
    },
    {   
        name: 'Jordan Access',
        vendor: 2271,
        price: 8000,
        dimensions: [39, 40, 42, 43, 44],
        colors: ['#E7E7E7', '#9D0DE0', '#5E599F', '#AD5E32', '#C9A5AB'],
        categories: ['street', 'run', 'football', 'basketball'],
        brand: 'rebook',
        season: 'winter',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 5, 16),
        photos: getPhotos('product14')
    },
    {   
        name: 'Jordan Nu Retro 1 Low',
        vendor: 2272,
        price: 8200,
        dimensions: [39, 40, 41, 43, 44],
        colors: ['#3F3F3F', '#E0B20D', '#E9E1EE', '#375B3D', '#A5B8C9'],
        categories: ['run', 'football'],
        brand: 'adidas',
        season: 'demi-season',
        description: getDescr(this.name),
        descriptionTwo: 'Подошва из пеноматериала упругая и мягкая.',
        type: ['man'],
        reviews: getReviews(),
        date: getDate(2023, 2, 22),
        photos: getPhotos('product15')
    },
]

// let productsTwo = [...products, ...products]

products.forEach((product, key) => {
    product['id'] = key + 1
})

module.exports = products